name: Debug

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'post message as text file to slack'
        required: true
        default: 'Hello World!'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo ${{ github.event.inputs.message }} > test1.txt'
      - run: 'echo ${{ github.event.inputs.message }} > test2.txt'
      - uses: ./
        id: upload_file
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNELS }}
          file_path: 'test*.txt'
          initial_comment: 'post by slack-upload-file'
